/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matecombatcliente;

/**
 *
 * @author Personal
 */
public class vistaMateCombat extends javax.swing.JFrame {

    /**
     * Creates new form vistaMateCombat
     */
    public vistaMateCombat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAtack = new javax.swing.JLabel();
        jlVidaBlanco = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pbPeleadorNegro = new javax.swing.JProgressBar();
        pbPeleadorBlanco = new javax.swing.JProgressBar();
        jlVidaNegro = new javax.swing.JLabel();
        jlSigno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfRespuesta = new javax.swing.JTextField();
        btnEnviarResultado = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jlTiempo = new javax.swing.JLabel();
        lbAlerta5 = new javax.swing.JLabel();
        jlNumero2 = new javax.swing.JLabel();
        jlNumero1 = new javax.swing.JLabel();
        tlTiempo1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbAlerta6 = new javax.swing.JLabel();
        lbTurno = new javax.swing.JLabel();
        imgRes = new javax.swing.JLabel();
        jlEsperando = new javax.swing.JLabel();
        btnHacerOperacion = new javax.swing.JButton();
        tfIp = new javax.swing.JTextField();
        jlResultado = new javax.swing.JLabel();
        imgRes2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mate Combat");
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(null);

        jlAtack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guantes.png"))); // NOI18N
        getContentPane().add(jlAtack);
        jlAtack.setBounds(240, 260, 128, 105);

        jlVidaBlanco.setBackground(new java.awt.Color(51, 255, 51));
        jlVidaBlanco.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlVidaBlanco.setText("100%");
        getContentPane().add(jlVidaBlanco);
        jlVidaBlanco.setBounds(20, 170, 49, 17);
        jlVidaBlanco.getAccessibleContext().setAccessibleName("lifePeleadorNegro");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/peleadorBlanco.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 190, 180, 250);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/peleadorNegro.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(410, 200, 180, 230);

        pbPeleadorNegro.setBackground(new java.awt.Color(51, 255, 51));
        pbPeleadorNegro.setForeground(new java.awt.Color(204, 204, 255));
        getContentPane().add(pbPeleadorNegro);
        pbPeleadorNegro.setBounds(400, 170, 146, 14);

        pbPeleadorBlanco.setBackground(new java.awt.Color(204, 204, 204));
        pbPeleadorBlanco.setForeground(new java.awt.Color(0, 204, 204));
        pbPeleadorBlanco.setValue(100);
        getContentPane().add(pbPeleadorBlanco);
        pbPeleadorBlanco.setBounds(75, 171, 146, 14);

        jlVidaNegro.setBackground(new java.awt.Color(51, 255, 51));
        jlVidaNegro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlVidaNegro.setText("100%");
        getContentPane().add(jlVidaNegro);
        jlVidaNegro.setBounds(550, 160, 44, 17);

        jlSigno.setBackground(new java.awt.Color(51, 255, 51));
        jlSigno.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlSigno.setText("+");
        getContentPane().add(jlSigno);
        jlSigno.setBounds(186, 112, 49, 44);

        jLabel9.setBackground(new java.awt.Color(51, 255, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Ingresa tu respuestas: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 440, 170, 17);

        tfRespuesta.setBackground(new java.awt.Color(153, 153, 255));
        tfRespuesta.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        tfRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRespuesta.setToolTipText("");
        tfRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRespuestaActionPerformed(evt);
            }
        });
        getContentPane().add(tfRespuesta);
        tfRespuesta.setBounds(270, 480, 57, 30);

        btnEnviarResultado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnviarResultado.setText("Enviar Resultado");
        btnEnviarResultado.setEnabled(false);
        btnEnviarResultado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarResultadoMouseClicked(evt);
            }
        });
        btnEnviarResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarResultado);
        btnEnviarResultado.setBounds(230, 520, 160, 25);

        btnIniciar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnIniciar.setText("Ingresar Ip");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarMouseClicked(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar);
        btnIniciar.setBounds(12, 519, 120, 25);

        jLabel12.setBackground(new java.awt.Color(51, 255, 51));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Tu eres el Peleador:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 440, 135, 20);

        jlTiempo.setBackground(new java.awt.Color(153, 153, 255));
        jlTiempo.setFont(new java.awt.Font("Trebuchet MS", 2, 36)); // NOI18N
        jlTiempo.setText("Blanco");
        jlTiempo.setToolTipText("");
        jlTiempo.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jlTiempo);
        jlTiempo.setBounds(450, 480, 109, 30);

        lbAlerta5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAlerta5.setText("Presiona para iniciar la pelea");
        lbAlerta5.setToolTipText("");
        getContentPane().add(lbAlerta5);
        lbAlerta5.setBounds(0, 440, 200, 17);

        jlNumero2.setBackground(new java.awt.Color(51, 255, 51));
        jlNumero2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlNumero2.setText("x2");
        getContentPane().add(jlNumero2);
        jlNumero2.setBounds(242, 112, 49, 44);

        jlNumero1.setBackground(new java.awt.Color(51, 255, 51));
        jlNumero1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlNumero1.setText("x1");
        getContentPane().add(jlNumero1);
        jlNumero1.setBounds(125, 112, 49, 44);

        tlTiempo1.setBackground(new java.awt.Color(204, 204, 204));
        tlTiempo1.setFont(new java.awt.Font("Tahoma", 3, 26)); // NOI18N
        tlTiempo1.setText("Mate Combact :D Gana con tu cerebro");
        tlTiempo1.setToolTipText("");
        getContentPane().add(tlTiempo1);
        tlTiempo1.setBounds(10, 10, 510, 61);

        jLabel16.setBackground(new java.awt.Color(51, 255, 51));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setText("=");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(298, 112, 49, 44);

        lbAlerta6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbAlerta6.setForeground(new java.awt.Color(51, 51, 51));
        lbAlerta6.setText("Datos del Juego:");
        lbAlerta6.setToolTipText("");
        getContentPane().add(lbAlerta6);
        lbAlerta6.setBounds(0, 90, 115, 17);

        lbTurno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTurno.setForeground(new java.awt.Color(0, 0, 255));
        lbTurno.setText("Jugador Blanco");
        lbTurno.setToolTipText("");
        getContentPane().add(lbTurno);
        lbTurno.setBounds(120, 90, 310, 22);
        getContentPane().add(imgRes);
        imgRes.setBounds(493, 170, 72, 0);

        jlEsperando.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlEsperando.setForeground(new java.awt.Color(255, 51, 51));
        jlEsperando.setText("Conecta con jugador 1..");
        jlEsperando.setToolTipText("");
        getContentPane().add(jlEsperando);
        jlEsperando.setBounds(12, 485, 200, 17);

        btnHacerOperacion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHacerOperacion.setText("Hacer operación");
        btnHacerOperacion.setEnabled(false);
        btnHacerOperacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHacerOperacionMouseClicked(evt);
            }
        });
        btnHacerOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHacerOperacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnHacerOperacion);
        btnHacerOperacion.setBounds(420, 520, 170, 25);

        tfIp.setBackground(new java.awt.Color(153, 153, 255));
        tfIp.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        tfIp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfIp.setToolTipText("");
        tfIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIpActionPerformed(evt);
            }
        });
        getContentPane().add(tfIp);
        tfIp.setBounds(240, 400, 110, 28);

        jlResultado.setBackground(new java.awt.Color(51, 255, 51));
        jlResultado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jlResultado.setText("???");
        getContentPane().add(jlResultado);
        jlResultado.setBounds(334, 98, 140, 72);
        getContentPane().add(imgRes2);
        imgRes2.setBounds(480, 80, 90, 87);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/k2.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(540, 0, 72, 87);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jLabel17.setRequestFocusEnabled(false);
        jLabel17.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 640, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRespuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRespuestaActionPerformed

    private void btnEnviarResultadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarResultadoMouseClicked

    }//GEN-LAST:event_btnEnviarResultadoMouseClicked

    private void btnEnviarResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarResultadoActionPerformed

    private void btnIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarMouseClicked

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnHacerOperacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHacerOperacionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHacerOperacionMouseClicked

    private void btnHacerOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHacerOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHacerOperacionActionPerformed

    private void tfIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaMateCombat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaMateCombat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaMateCombat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaMateCombat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaMateCombat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnEnviarResultado;
    public javax.swing.JButton btnHacerOperacion;
    public javax.swing.JButton btnIniciar;
    public javax.swing.JLabel imgRes;
    public javax.swing.JLabel imgRes2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jlAtack;
    public javax.swing.JLabel jlEsperando;
    public javax.swing.JLabel jlNumero1;
    public javax.swing.JLabel jlNumero2;
    public javax.swing.JLabel jlResultado;
    public javax.swing.JLabel jlSigno;
    public javax.swing.JLabel jlTiempo;
    public javax.swing.JLabel jlVidaBlanco;
    public javax.swing.JLabel jlVidaNegro;
    public javax.swing.JLabel lbAlerta5;
    public javax.swing.JLabel lbAlerta6;
    public javax.swing.JLabel lbTurno;
    public javax.swing.JProgressBar pbPeleadorBlanco;
    public javax.swing.JProgressBar pbPeleadorNegro;
    public javax.swing.JTextField tfIp;
    public javax.swing.JTextField tfRespuesta;
    public javax.swing.JLabel tlTiempo1;
    // End of variables declaration//GEN-END:variables
}
